services:
  vectra-api:
    volumes:
      - ..:/workspaces/Vectra:cached
    deploy: !!null
    environment:
      - NVIDIA_VISIBLE_DEVICES=none

  vectra-worker:
    deploy: !!null
    environment:
      - NVIDIA_VISIBLE_DEVICES=none

  vectra-ollama:
    deploy: !!null
    environment:
      - NVIDIA_VISIBLE_DEVICES=none

  vectra-whisper:
    deploy: !!null
    environment:
      - NVIDIA_VISIBLE_DEVICES=none

  vectra-frontend:
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
