services:
  vectra-api:
    volumes:
      - ..:/workspaces/Vectra:cached
    deploy:
      resources:
        reservations:
          devices: []

  vectra-worker:
    deploy:
      resources:
        reservations:
          devices: []

  vectra-ollama:
    deploy:
      resources:
        reservations:
          devices: []

  vectra-whisper:
    deploy:
      resources:
        reservations:
          devices: []

  vectra-frontend:
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
