services:
  vectra-api:
    volumes:
      - ..:/workspaces/Vectra:cached
    runtime: runc
    environment:
      - NVIDIA_VISIBLE_DEVICES=none
    deploy:
      resources:
        reservations:
          devices: []

  vectra-worker:
    runtime: runc
    environment:
      - NVIDIA_VISIBLE_DEVICES=none
    deploy:
      resources:
        reservations:
          devices: []

  vectra-ollama:
    runtime: runc
    environment:
      - NVIDIA_VISIBLE_DEVICES=none
    deploy:
      resources:
        reservations:
          devices: []

  vectra-whisper:
    runtime: runc
    environment:
      - NVIDIA_VISIBLE_DEVICES=none
    deploy:
      resources:
        reservations:
          devices: []

  vectra-frontend:
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
